# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "nixbox64"
  config.vm.network :forwarded_port, guest: 80, host: 8080
  config.ssh.forward_agent = true
  config.vm.synced_folder ".", "/vagrant_data"

  # config.vm.network :private_network, ip: "192.168.33.10"
  # config.vm.network :public_network
end
